# -*- coding: utf-8 -*-
"""code_part

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qAaZcaoE6xoc8NgEP4ewiJC38sGS9bXn
"""

import numpy as np
import nibabel as nib
import glob
from tensorflow.keras.utils import to_categorical
import matplotlib.pyplot as plt
from tifffile import imsave

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()



#dataset path address=>> 

test_image_T1= nib.load("").get_fdata()
print(test_image_T1.max())
test_image_T1= scaler.fit_transform(test_image_T1.reshape(-1, test_image_T1.shape[-1])).reshape(test_image_T1.shape)

test_image_T1ce= nib.load("").get_fdata()
print(test_image_T1ce.max())
test_image_T1ce= scaler.fit_transform(test_image_T1ce.reshape(-1, test_image_T1ce.shape[-1])).reshape(test_image_T1ce.shape)

test_image_T2= nib.load("").get_fdata()
print(test_image_T2.max())
test_image_T2= scaler.fit_transform(test_image_T2.reshape(-1, test_image_T2.shape[-1])).reshape(test_image_T2.shape)

test_image_flair= nib.load("").get_fdata()
print(test_image_flair.max())
test_image_flair= scaler.fit_transform(test_image_flair.reshape(-1, test_image_flair.shape[-1])).reshape(test_image_flair.shape)

test_mask= nib.load("").get_fdata()
test_mask= test_mask.astype(np.uint8)
print(np.unique(test_mask))

test_mask[test_mask == 4]= 3
print(np.unique(test_mask))



import random
n_slice= random.randint(0, test_mask.shape[2])
plt.figure(figsize= (12, 8))

plt.subplot(231)
plt.imshow(test_image_T1[:,:,n_slice], cmap='gray')
plt.title('Image T1')

plt.subplot(232)
plt.imshow(test_image_T1ce[:,:,n_slice], cmap='gray')
plt.title('Image T1ce')

plt.subplot(233)
plt.imshow(test_image_T2[:,:,n_slice], cmap='gray')
plt.title('Image T2')

plt.subplot(234)
plt.imshow(test_image_flair[:,:,n_slice], cmap='gray')
plt.title('Image flair')

plt.subplot(235)
plt.imshow(test_mask[:,:,n_slice])
plt.title('Mask')

plt.show()

